#controllers:
#    resource: ../src/User/Controller/
#    type: attribute

controllers:
    resource: '../src/UI/Controller'
    type: annotation

#person:
#    resource: '../src/UI/Controller/Person'
#    type: annotation

api_login_check:
    path: /api/login_check
