#controllers:
#    resource: ../src/User/Controller/
#    type: attribute

user:
    resource: '../src/UI/Controller/User'
    type: annotation

person:
    resource: '../src/UI/Controller/Person'
    type: annotation

api_login_check:
    path: /api/login_check
