trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: Docker@2
  inputs:
    containerRegistry: 'Azure Container Registry'
    repository: 'panthir'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'