trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadSecureFile@1
  name: envFile
  displayName: 'Download .env file'
  inputs:
    secureFile: '.env.prod'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'docbuilder storage'
    azureContainerRegistry: '{"loginServer":"docbuilderbackend.azurecr.io", "id" : "/subscriptions/08a0b74a-f117-40c6-a944-63fbdbb675d8/resourceGroups/docbuilder-storage/providers/Microsoft.ContainerRegistry/registries/docbuilderbackend"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker-compose --env-file $(envFile.secureFilePath) build'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'docbuilder storage'
    azureContainerRegistry: '{"loginServer":"docbuilderbackend.azurecr.io", "id" : "/subscriptions/08a0b74a-f117-40c6-a944-63fbdbb675d8/resourceGroups/docbuilder-storage/providers/Microsoft.ContainerRegistry/registries/docbuilderbackend"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
    includeSourceTags: true
    includeLatestTag: true

