version: "3.8"

services:
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - ENV=${ENV}
        - DB_NAME=${POSTGRES_DB}
        - DB_USER=${POSTGRES_USER}
        - DB_PASS=${POSTGRES_PASSWORD}
        - DB_HOST=${POSTGRES_HOST}
        - DB_PORT=${POSTGRES_PORT}
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/
    networks:
      - symfony
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - redis

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
      args:
        - NGINX_HOST_HTTP_PORT=${NGINX_HOST_HTTP_PORT}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./backend:/var/www:rw
    depends_on:
      - php-fpm
      - redis
    networks:
      - symfony

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    build:
      context: ./.docker/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
      - symfony

  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
    networks:
      - symfony

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - redis

volumes:
  db_data:
#  backend:
  cache:
    driver: local

networks:
  symfony:
  redis: