export { default as HomeView } from './HomeView.vue';
export { default as PersonEditView } from '~/views/person/PersonEditView.vue';
export { default as PersonListView } from '~/views/person/PersonListView.vue';
export { default as UserListView } from '~/views/user/UserListView.vue';
export { default as UserEditView } from '~/views/user/UserEditView.vue';
export { default as LoginView } from '~/views/common/LoginView.vue';
export { default as RegisterView } from '~/views/common/RegisterView.vue';
export { default as FinancialEditView } from '~/views/financial/FinancialEditView.vue';
export { default as FinancialInstallmentTable } from '~/views/financial/FinancialInstallmentTable.vue';
